### ISSUE TITLE
proposition : éviter la superposition des m-toast

### ISSUE THREAD

**Issue by matthiastran** [ulaval/modul#201]
Aujourd'hui, il est possible d'avoir plusieurs m-toast sur la même page et de les positionner sur la page.

**Problématique** :
Lorsque deux m-toast ont la même position sur la page, ils se superposent et l'un cache l'autre.

**Besoin** :
Il faudrait pouvoir paramétrer les m-toast pour qu'ils ne se superposent pas.

**Lien vers le billet Jira** : 
https://jira.dti.ulaval.ca/browse/R11-979

**Comment by guignol1981** [comment]
je vais la prendre celle la
