### ISSUE TITLE
proposition: MTable - Réorganiser les colonnes

### ISSUE THREAD

**Issue by jpguilmette** [ulaval/modul#220]
**Description du besoin**
- Ajouter au MTable la fonctionnalité de pouvoir cacher des colonnes. 
- Ajouter au MTable la fonctionnalité de pouvoir changer l'ordre des colonnes. 

**Description sommaire de la solution proposée**
Ajouter au MTable un bouton ouvrant une modal contenant la liste des columns. Permettant de les cacher/afficher et de changer l'ordre (par DragDrop préférablement)

**Captures d'écran**
![screencapture-xd-adobe-view-93bfead6-9c2f-4c0b-4e1c-4e9ec8728990-e58e-screen-04d0578f-9117-4120-b284-9b5568d3c1ff-Web-1920-9-2020-02-04-13_30_01 (1)](https://user-images.githubusercontent.com/25248749/73777190-0b90fe80-4757-11ea-9e34-65a53073c8be.png)

**Liens vers les récits Jira**

**Comment by chuckmah** [comment]
@jipigi  il me semble que vous avez-vous quelque chose de semblable dans Brio non?

**Comment by jipigi** [comment]
@chuckmah non, on en a parlé mais finalement, on a réussi jusqu'à  maintenant à limiter le nombre de colonnes des tableaux, mais la solution est intéressante et je pense qu'on s'en servira à moment donné.
