### ISSUE TITLE
proposition: Creer un package m-modul-icons et permettre l'enregistrement a-la-pièce des icones

### ISSUE THREAD

**Issue by chuckmah** [ulaval/modul#225]
**Description du besoin**
On désire avoir un moyen simple d'ajouter, de consulter et d'utiliser les icones dans MODUL .

Actuellement les icônes de MODUL sont tous placés dans un gros fichier svg `sprites-default.svg`  qui est loadé au startup par le service `svg.addInternalSprites()`  dans le plugin `SvgPlugin`. Ceci ne permet pas de bien faire du code splitting (ie. les applications doivent toujours loader tous les icones au startup dans le bundle principal). 

L'idéal serait de pouvoir loader seulement les icônes qui sont utilisés dans un composant donnée afin de diminuer la taille des fichiers. Par exemple: si une application possède une interface d'admin et d'utilisateur je ne veut pas que les utilisateurs aient à télécharger les icônes de l'interface d'admin

**Description sommaire de la solution proposée**

La solution proposée se ferait en étape:

1. Création du package `@ulaval/modul-icons` sous le repertoire /packages/modul-icons et ajout de des icones  de  `sprites-default.svg`  en fichier séparer. Par exemple l'icone `m-svg-add-circle-filled` serait dans le répertoire /svg/add-circle-filled.svg. S'inspirer des librairie d'icone existante comme Font-Awesome (https://github.com/FortAwesome/Font-Awesome/tree/master/svgs/regular)

2. Replacer le service `addInternalSprites` du plugin `SvgPlugin` par une methode qui permet d'ajouter les icones a la pièce  du genre

```
import SvgAddCircleFilled from '@ulaval/modul-icons/svg/add-circle-filled.svg ';

[...]

svg.addSvg('add-circle-filled',  SvgAddCircleFilled );
```

3. Dans chaque composante MODUL, on devrait ajouter le code nécessaire a enregistrer les icônes utilisé dans le template.
Par exemple dans le datepicker , vu qu'on utilise le m-svg__calendar on devrait enregistrer dans le fichier datepicker.ts les icônes a l'aide du service: 

```
import SvgCalendar from '@ulaval/modul-icons/svg/calendar.svg ';

[...]

svg.addSvg('m-svg__calendar',  SvgCalendar );
```

Si l'icone a déjà été enregistrer ne rien faire (pas d’enregistrement en double)

4. La documentation d'iconographie de modul-website devra être mis a jour et a chaque fois qu'on ajoute un svg au projet , ceci devrait être disponible dans la recherche d'icone 

https://ulaval.github.io/modul/Normes/graphique/iconographie/icons

**Captures d'écran**
Si possible, ajoutez des captures d'écran pour démontrer la nouvelle fonctionnalité.

**Liens vers les récits Jira**
https://jira.dti.ulaval.ca/browse/MPOPO-869

**Comment by vidal7** [comment]
Super idée. Ça va améliorer le tree-shaking. Aussi, cela va éliminer les sprites qui sont dur à maintenir et où nous n'avons pas d'idée si l'icône existe déjà ou pas. Je paris qu'il y a des icônes en double dans le sprite.

**Comment by chuckmah** [comment]
> Super idée. Ça va améliorer le tree-shaking. Aussi, cela va éliminer les sprites qui sont dur à maintenir et où nous n'avons pas d'idée si l'icône existe déjà ou pas. Je paris qu'il y a des icônes en double dans le sprite.

exact, De plus l'avantage serait de centraliser tous les icônes dans un seul et unique package où on pourrait y mettre tous les icônes (... pas seulement ceux de MODUL mais aussi ceux des projets)
