### ISSUE TITLE
proposition: permettre l'utilisation locale des composantes

### ISSUE THREAD

**Issue by chuckmah** [ulaval/modul#226]
**Description du besoin**
Au lieu d'un enregistrement global des composantes , il serait bien de pouvoir les utiliser  de facon local afin de permettre les optimisation de webpack notamment le treeshaking et le code splitting.

**Description sommaire de la solution proposée**
Voir https://fr.vuejs.org/v2/guide/components-registration.html#Creation-locale pour la définition d'une création locale et comment l'ajouter à l'option `components`.

Il faudrait prendre chaque Plugin de `/component` et déclarer les composantes qui sont utilisées dans les options `components` de chaque component

Par exemple pour boutton.ts
```
import { Icon } from '../icon/icon';
import  { Spinner }  from '../spinner/spinner';

[...]

@Component({
    component: [
        ICON_NAME: Icon,
        SPINNER_NAME: Spinner 
    ]
})

```

Ensuite mettre un message warning dans le ButtonPlugin spécifiant qu'il est préférable d'utilisation l'installation local a l'utilisation du plugin

Il faudrait changer le storybook et website pour enlever le ButtonPlugin  et remplacer par la solution.

Faire cela pour tout les composantes MODUL.

**Captures d'écran**
Si possible, ajoutez des captures d'écran pour démontrer la nouvelle fonctionnalité.

**Liens vers les récits Jira**
Si vous êtes un contributeur interne, ajouter les liens vers vos billets Jira.

**Comment by vidal7** [comment]
J'aimerais faire ce travail également dans Brio car pour l'instant, le chunk initiale contient modUL au complet. En déclarant les composants localement, il y aurait également du tree shaking. Par contre, cette tâche sera colossale à faire. Je me demande si on ne pourrait pas programmer quelque chose d'automatique. Je pense à quelque chose qui parse le html, identifie tous les composants modUL <m-*> et ensuite l'ajoute dans le typescript avec ts-morph. Je pense que ça pourrait bien se faire. Si on avait cet outil, modUL et Brio pourrait en profiter.
