### ISSUE TITLE
bogue: [m-select] La navigation clavier (tabulation) est bloquée par le m-select

### ISSUE THREAD

**Issue by jipigi** [ulaval/modul#317]
**Description du bogue / Describe the bug**
Lorsque l'on utilise la tabulation pour naviguer dans les éléments interatifs d'un formulaire, il est impossible de donner le focus à un élément qui suit le m-select (ou qui le précède si la navigation est inversée).

**Reproduction / To Reproduce**
Étapes pour reproduire le problème:
1. Créer un formulaire contenant un m-select avec d'autres champs avant et après
2. Utilise la touche tabulation pour naviguer jusqu'au m-select
3. Une fois que le m-select a reçu le focus, enfonce de nouveau la touche tabulation (ou shift+tab)
4. Le focus reste sur le m-select

**Comportement attendu / Expected behavior**
Le focus passe au champ suivant ou précédent.

**Versions affectées / Affected Versions**
 - Package: modul-components
 - version: 1.0.0

**Environnement / Environment**
 - Appareil : tous 
 - OS: tous 
 - Navigateur : tous

**Comment by chuckmah** [comment]
Tu es sur quel version de modul exactement ? je me demande si c'est pas le keydown.prevent de la 1.1.8 @setur52  ?

**Comment by setur52** [comment]
c'est déjà réglé dans une autre PR

**Comment by jipigi** [comment]
Réglé par #318
