### ISSUE TITLE
proposition: Deux nouvelles pages d'erreur

### ISSUE THREAD

**Issue by simardo** [ulaval/modul#33]
**Description du besoin**
Gestion des erreurs suivantes: 503 (ressource non-disponible) et 409 (optimistic locking)

**Description sommaire de la solution proposée**
Deux nouvelles pages d'erreur seront ajoutée au repo. 
m-error-resource-unavailable
m-error-conflict

**Captures d'écran**
m-error-resource-unavailable
Titre (selon ce qu'il y a déjà dans MPO - configurable): Cette section de monPortail est actuellement indisponible.
Détail: Nous travaillons à rétablir la situation dans les meilleurs délais.
Icône: 
![image](https://user-images.githubusercontent.com/1334127/64628476-782dea00-d3bf-11e9-9096-645bcb3b91f4.png)

m-error-conflict
Titre (à valider): La donnée sur laquelle vous travaillez a été modifiée par un autre utilisateur.
Détail: Les modifications que vous avez apportées n'ont pas été enregistrées. Veuillez les soumettre à nouveau.
![image](https://user-images.githubusercontent.com/1334127/64628552-998ed600-d3bf-11e9-9ce8-d4304659e2bb.png)

**Liens vers les récits Jira**
https://jira.dti.ulaval.ca/browse/P387-1066

**Comment by chuckmah** [comment]
Merci @simardo !

Par la bande on pourra en profiter pour voir à créer la documentation dans website pour tous les pages d'erreurs et documenter en quoi ces pages sont différente de m-error-technical-difficulty
