### ISSUE TITLE
bogue: MSteppersItem ne semble pas exporté correctement [1.2.0-RC.1]

### ISSUE THREAD

**Issue by joasneo** [ulaval/modul#335]
**Description du bogue / Describe the bug**
J'utilise la version 1.2.0-RC.1. J'ai besoin d'utiliser le MSteppers. Le MSteppersItem ne semble pas exporté correctement.

**Reproduction / To Reproduce**
Étapes pour reproduire le problème:
1. Importer les composantes MSteppers et MSteppersItem :
import { MSteppers, MSteppersItem } from "@ulaval/modul-components";
2. Utiliser le code de base 
&lt;m-steppers&gt;
      &lt;m-steppers-item
        v-for=" ...
3. Comportement observé
Dans la console :  Unknown custom element: &lt;m-steppers-item&gt;

**Comportement attendu / Expected behavior**
Que l'élément m-steppers-item soit accessible comme les autres.

**Captures d'écran / Screenshots**
![code](https://user-images.githubusercontent.com/20706687/83659214-3e29f700-a591-11ea-8d67-3055c1cf8066.jpg)
![console](https://user-images.githubusercontent.com/20706687/83659216-3e29f700-a591-11ea-8b31-ee73c3a8332c.jpg)

**Versions affectées / Affected Versions**
 - Package: modul-components
 - version: 1.2.0-RC.1

**Environnement / Environment**
 - Appareil : ordinateur portable
 - OS: Windows 7
 - Navigateur: Chrome 83

**Comment by chuckmah** [comment]
Salut, c'est un oubli de ma part, il faudrait l'exporter du fichier lib.ts (en develop)

https://github.com/ulaval/modul/blob/develop/packages/modul-components/src/lib.ts

@guignol1981  tu peux t'en occuper?

**Comment by guignol1981** [comment]
Oui, je fais une release immédiatement après?

**Comment by guignol1981** [comment]
@joasneo  La version 1.2.0-RC.2 exporte le m-steppers correctement

**Comment by guignol1981** [comment]
@joasneo voilà c'est reglé avec la RC.3. Merci :)

**Comment by joasneo** [comment]
Merci beaucoup !!!
