### ISSUE TITLE
proposition: MSelect sélection multiple

### ISSUE THREAD

**Issue by jpguilmette** [ulaval/modul#36]
**Description du besoin**
Besoin, une liste déroulante permettant la sélection multiple.
+Avoir une option pour sélectionner tout

**Description sommaire de la solution proposée**
Une composition de MSelect (pour sélectionner) et de MChip (pour les sélections)

**Liens vers les récits Jira**
https://jira.dti.ulaval.ca/browse/MODUL-771

**Comment by jipigi** [comment]
Voilà l’état des specs suite à notre rencontre :
https://wiki.dti.ulaval.ca/pages/viewpage.action?pageId=104509222

La description est une ébauche de ce qui devrait se retrouver dans Website. 
Je vous invite à consulter les wireframes pour alimenter la discussion et valider ce qu’on s’est dit.
J’ai aussi précisé les règles de mise à jour du modèle et de navigation clavier (il y a du stock là dedans, il faudra peut-être prioriser les principales).
