### ISSUE TITLE
proposition: Improvements to getControl in FormGroup

### ISSUE THREAD

**Issue by jsroy19** [ulaval/modul#4]
**Is your feature request related to a problem? Please describe.**
if there is ever the need to "find" a control, that is get it if it exists, it would be nice to have a methods that doesn't throw if the control is not found.

**Describe the solution you'd like**
The current implementation is :
```
public getControl<T = any>(name: string): AbstractControl<T> {
     if (this._controls[name] !== undefined) {
            return this._controls[name] as AbstractControl<T>;
        } else {
            throw Error(`There is no control with the name ${name} in this group`);
        }
}
```
That method could be renamed getControlOrThrow or something in the same style and another method getControl could juste return an undefined when not found.
Another naming option could be getControl (this throws) vs findControl (this does not throw)

**Additional context**
here is an exemple of the usage I talk about :
```
try {
    controle = this.formGroup.getControl(this.ID_FORM_CONTROL_REPONSE_PREFIX + 
         this.reponse.idElementReponseQuestionnaire) as FormControl<string>;
} catch (error) {
    controle = new FormControl<string>(this.getValidateurs(this.reponse), { initialValue: 
    this.reponse.reponseCourte ? this.reponse.reponseCourte : '' });
    this.formGroup.addControl(this.ID_FORM_CONTROL_REPONSE_PREFIX + 
        this.reponse.idElementReponseQuestionnaire, controle);
}
```

# #1 :P

**Comment by chuckmah** [comment]
Selon moi on pourrait faire un breaking change et tout simplement enlever le throw et retourner null a la place.. @guignol1981  qu'en pense tu?

**Comment by guignol1981** [comment]
je vais l'essayer

**Comment by guignol1981** [comment]
Je pense que c'est un erreur de design de ne pas savoir si un control est déjà ajouté ou non.

**Comment by setur52** [comment]
@chuckmah Finalement tu voulais faire un breaking change hahaha je crois qu'on peut fermer cette issue?
