### ISSUE TITLE
proposition: Pouvoir recadrer des images

### ISSUE THREAD

**Issue by jomat76** [ulaval/modul#48]
**Description du besoin**
Être en mesure de cropper une image. Utile lors de la sélection de la photo de profil dans Brio.
https://wiki.dti.ulaval.ca/pages/viewpage.action?pageId=101650385
https://k907xn.axshare.com/#g=1&p=_diteur_de_photo

**Description sommaire de la solution proposée**
Création d'un compostant m-photo-editor qui utilisera croppie. La librairie a préalablement été approuvé par @chuckmah.

**Captures d'écran**
Si possible, ajoutez des captures d'écran pour démontrer la nouvelle fonctionnalité.

**Liens vers les récits Jira**
https://jira.dti.ulaval.ca/browse/ENA2-7833

**Comment by chuckmah** [comment]
@jipigi  as-tu besoin qu'on se fasse un kickoff avant de dev ? de mon côté tout est ok vu qu'on s'est déja rencontré.

**Comment by jomat76** [comment]
> @jipigi as-tu besoin qu'on se fasse un kickoff avant de dev ? de mon côté tout est ok vu qu'on s'est déja rencontré.

Lorsqu'on s'était rencontré, on a décidé quel librairie utiliser mais on a pas parlé de la portée et des props de notre composant. Ça pourrait donc être une bonne idée de se faire une petite rencontre.
