### ISSUE TITLE
bogue: La valeur séléctionnée d'une liste déroulante filtrable est réinitialisée lorsqu'on efface un caractère du filtre

### ISSUE THREAD

**Issue by jipigi** [ulaval/modul#60]
**Description du bogue / Describe the bug**
La valeur séléctionnée d'une liste déroulante filtrable est réinitialisée lorsqu'on efface un caractère du filtre. 

**Reproduction / To Reproduce**
Étapes pour reproduire le problème:
- Sélectionner une valeur dans une liste déroulante filtrable
- Enfoncer n'importe quelle touche (<backspace> ou une lettre, <suppr>, etc.)

La valeur sélectionnée précédemment est réinitialisée.

**Comportement attendu / Expected behavior**
La liste d'options est filtrée en fonction de la nouvelle valeur saisie dans le champ de recherche. La valeur est modifié seulement à la sortie du champ si la chaine de caractères saisie dans le champ de recherche correspond exactement à une des valeurs de la liste d'options.

**Captures d'écran / Screenshots**
Brio : https://i.imgur.com/HkvElvk.gifv
Storybook MODUL : https://i.imgur.com/NjNUGmI.gifv
AEL : le problème ne se produit pas (par contre, la liste d'option est réduite à une seule ligne) https://i.imgur.com/6V1Hy0y.gifv

**Versions affectées / Affected Versions**
 - Package: modul-components
 - version: béta 125 (mais présent depuis quelques releases)

**Environnement / Environment**
 - Appareil : tous 
 - OS: tous
 - Navigateur : tous 

**Liens vers les récits Jira**
-

**Comment by jpguilmette** [comment]
@jipigi J'ai été confronté à ce problème dans Admission cette semaine. Un workaround est d'utiliser la prop clear-model-on-selected-text de MDropdown qui empêche ceci. Sa valeur par défaut est à vrai
