### ISSUE TITLE
proposition: Ajouter le 'clear' de la valeur choisi dans le m-select

### ISSUE THREAD

**Issue by mturcotteDTI** [ulaval/modul#61]
**Description du besoin**
Ajouter la fonctionnalité dans le m-select que lorsqu'on choisi une valeur, un X apparait au bout de la ligne (comme le search-field) qui enlèverait la valeur choisi du m-select et remettrais la valeur du placeholder. 

**Description sommaire de la solution proposée**
Bonifier le m-select pour ajouter la fonctionnalité en option au composant

**Captures d'écran**
![Capture](https://user-images.githubusercontent.com/34482214/65702886-c4308e00-e051-11e9-8d3d-7b066c9effd0.PNG)

**Liens vers les récits Jira**
https://jira.dti.ulaval.ca/browse/ENA2-7770

**Comment by jipigi** [comment]
Tel que discuté hier : 
- Afficher le X : 
-- m-select : seulement lorsqu'une valeur est sélectionnée.
-- m-select filterable = true (à venir) : Lorsqu'une valeur est sélectionnée ou lorsque le champ texte du filtre contient au moins un caractère.
- Le X est affiché quel que voit l'état de la liste (ouverte ou fermée).
- L'action sur le X désélectionne la valeur sélectionnée, et vide le champ filtre lorsqu'applicable.
- Il est possible de déclencher l'action avec les touche <suppr> ou <backspace> lorsque le champ détient le focus.
- Afficher le X dans le champ, aligné à droite, centré dans une zone de 44 px. Le m-icon-button devrait faire la job de préserver le 44px de large pour la zone de clic. Donner une largeur de 11px au X comme dans le m-searchfield.

**Comment by mturcotteDTI** [comment]
Salut, 
Merci pour le résumé! Il y a seulement le 44px de large par 44 px de haut. Dans searchfield c'est le bouton de recherche qui est comme ça pas le X. J'ai mis la même chose pour dans le m-select que le X du searchfield. Vous me direz si c'est correct
