### ISSUE TITLE
proposition: Mise à niveau de Portal et de son fonctionnement

### ISSUE THREAD

**Issue by jpguilmette** [ulaval/modul#70]
**Description du besoin**
Portal est à la version 1.1.1, il faudrait le migrer à la version la plus récente (actuellement 2.1.6).
Il faut aussi un refactor de l'écosystème de la mixin et du plugin Portal.

**Description sommaire de la solution proposée**
* Un nouveau composant modul-portal qui inclurait &lt;portal> et &lt;transition>.
* Un nouveau set d'événements émits par ce composant selon les hook JS de Transition
https://fr.vuejs.org/v2/guide/transitions.html#hooks-JavaScript
* Le retrait des setTimeout et TransitionDuration
* Le retrait du Mixins Portal
* L'ajustement des composantes utilisant le Mixins Portal (MDialog, MModal, MOverlay, MPopper, MSidebar et MToast)

**Comment by vidal7** [comment]
Vue3 s'en vient avec son propre Portal built-in. Il faudait évaluer cette possibilité aussi avant de faire un refactor portal en vue2. https://vueschool.io/articles/vuejs-tutorials/portal-a-new-feature-in-vue-3/
